 version: '3.7'
 services:
   dashboard:
     build: 
       context: ./
     # Name for local and official deployment.  
     container_name: PCNonline_dash_localtest
     hostname: PCNonline_dash_localtest
