 version: '3.7'
 services:
   dashboard:
     ports:
       - 5000:80
     networks:
       - network
     build: 
       context: ./
     container_name: PCNonline_dash_local
     hostname: PCNonline_dash_local
 networks:
   network:
     driver: bridge
